import type { Lang } from "../../lib/i18n";

/**
 * The 88 constellations in Bangla. The API names them as astropy's get_constellation() does, which
 * includes three misspellings ("Chamaleon", "Ophiucus", "Pisces Austrinus") and "Crux " with a trailing
 * space, so both spellings are listed. A constellation keeps the Bangla name people actually use where
 * there is one (the twelve of the zodiac, কালপুরুষ, সপ্তর্ষিমণ্ডল, ত্রিশঙ্কু); Bangla Wikipedia gives
 * Sanskrit names for the rest (ধ্রুবমাতা for Andromeda), but few readers know them, so those are
 * transliterated, as the atlas does for object names.
 */
const BN: Record<string, string> = {
  Andromeda: "অ্যান্ড্রোমিডা",
  Antlia: "অ্যান্টলিয়া",
  Apus: "এপাস",
  Aquarius: "কুম্ভ",
  Aquila: "অ্যাকুইলা",
  Ara: "আরা",
  Aries: "মেষ",
  Auriga: "অরাইগা",
  Boötes: "বুটিস",
  Bootes: "বুটিস",
  Caelum: "সিলাম",
  Camelopardalis: "ক্যামেলোপার্ডালিস",
  Cancer: "কর্কট",
  "Canes Venatici": "ক্যানেস ভেনাটিসি",
  "Canis Major": "ক্যানিস মেজর",
  "Canis Minor": "ক্যানিস মাইনর",
  Capricornus: "মকর",
  Carina: "ক্যারিনা",
  Cassiopeia: "ক্যাসিওপিয়া",
  Centaurus: "সেন্টরাস",
  Cepheus: "সেফিয়াস",
  Cetus: "সিটাস",
  Chamaeleon: "ক্যামেলিয়ন",
  Chamaleon: "ক্যামেলিয়ন",
  Circinus: "সারসিনাস",
  Columba: "কলাম্বা",
  "Coma Berenices": "কোমা বেরেনিসিস",
  "Corona Australis": "করোনা অস্ট্রালিস",
  "Corona Borealis": "করোনা বোরিয়ালিস",
  Corvus: "করভাস",
  Crater: "ক্রেটার",
  Crux: "ত্রিশঙ্কু",
  Cygnus: "সিগনাস",
  Delphinus: "ডেলফিনাস",
  Dorado: "ডোরাডো",
  Draco: "ড্রাকো",
  Equuleus: "ইকুউলিয়াস",
  Eridanus: "এরিডানাস",
  Fornax: "ফরন্যাক্স",
  Gemini: "মিথুন",
  Grus: "গ্রুস",
  Hercules: "হারকিউলিস",
  Horologium: "হোরোলোজিয়াম",
  Hydra: "হাইড্রা",
  Hydrus: "হাইড্রাস",
  Indus: "ইন্ডাস",
  Lacerta: "ল্যাসার্টা",
  Leo: "সিংহ",
  "Leo Minor": "লঘু সিংহ",
  Lepus: "লেপাস",
  Libra: "তুলা",
  Lupus: "লুপাস",
  Lynx: "লিংক্স",
  Lyra: "লাইরা",
  Mensa: "মেনসা",
  Microscopium: "মাইক্রোস্কোপিয়াম",
  Monoceros: "মনোসেরস",
  Musca: "মাসকা",
  Norma: "নর্মা",
  Octans: "অক্টানস",
  Ophiuchus: "অফিউকাস",
  Ophiucus: "অফিউকাস",
  Orion: "কালপুরুষ",
  Pavo: "পাভো",
  Pegasus: "পেগাসাস",
  Perseus: "পারসিয়াস",
  Phoenix: "ফিনিক্স",
  Pictor: "পিক্টর",
  Pisces: "মীন",
  "Piscis Austrinus": "দক্ষিণ মীন",
  "Pisces Austrinus": "দক্ষিণ মীন",
  Puppis: "পাপিস",
  Pyxis: "পিক্সিস",
  Reticulum: "রেটিকুলাম",
  Sagitta: "স্যাজিটা",
  Sagittarius: "ধনু",
  Scorpius: "বৃশ্চিক",
  Sculptor: "স্কাল্পটর",
  Scutum: "স্কুটাম",
  Serpens: "সার্পেন্স",
  Sextans: "সেক্সট্যান্স",
  Taurus: "বৃষ",
  Telescopium: "টেলিস্কোপিয়াম",
  Triangulum: "ট্রায়াঙ্গুলাম",
  "Triangulum Australe": "ট্রায়াঙ্গুলাম অস্ট্রালি",
  Tucana: "টুকানা",
  "Ursa Major": "সপ্তর্ষিমণ্ডল",
  "Ursa Minor": "লঘু সপ্তর্ষিমণ্ডল",
  Vela: "ভেলা",
  Virgo: "কন্যা",
  Volans: "ভোলান্স",
  Vulpecula: "ভালপেকুলা",
};

/** A constellation's name in the reader's language; a name it does not know is returned as given. */
export function constellationName(name: string, lang: Lang): string {
  return lang === "bn" ? (BN[name.trim()] ?? name) : name;
}
